export const KEYS = {
  users: 'users',
  systemAdministrators: 'systemAdministrators',
  businessOwners: 'businessOwners',
  businessOwnerDetails: 'businessOwnerDetails',
  cashiers: 'cashiers',
  storeInstances: 'storeInstances',
  products: 'ownerProducts',
  services: 'ownerServices',
  productCategories: 'productCategories',
  serviceCategories: 'serviceCategories',
  invoices: 'invoices',
  productSales: 'productSales',
  serviceSales: 'serviceSales',
};
